name: website
version: 0.0.1
description: My website.
dependencies:
  path: any
  vector_math: any
  json_annotation: ^0.2.3
dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.3.0
  json_serializable: ^0.5.4
  dio: ^1.0.6
