name: website
version: 0.0.1
description: My website.
dependencies:
  path: ^1.6.4
  vector_math: ^2.0.8
  json_annotation: ^3.0.1
dev_dependencies:
  build_runner: ^1.8.0
  build_web_compilers: ^2.9.0
  test: ^1.14.2
